### ISSUE TITLE
see if I can get round docker / virtualbox container scalability defect

### ISSUE THREAD

**Issue by jameshnsears** [jameshnsears/xqa-documentation#59]
[jsears@localhost xqa-perf]$ docker logs dev_xqa-shard_6
2018-05-07 14:22:22,137      INFO --- [          MainThread]:                  __init__,  25: shard/9636cc8a
2018-05-07 14:22:29,050      INFO --- [          MainThread]:            _server_create,  42: pid=7; stdout=b''; stderr=b'/tmp/.basex: writing new configuration file.\nConnection failed (port: 1984).\n'
Traceback (most recent call last):
  File "xqa/shard.py", line 185, in <module>
    Container(Shard()).run()
  File "xqa/shard.py", line 28, in __init__
    self._storage_service = StorageService()
  File "/opt/xqa-shard/xqa/storage/storage_service.py", line 23, in __init__
    self._session_open()
  File "/opt/xqa-shard/xqa/storage/storage_service.py", line 57, in _session_open
    configuration.storage_password)
  File "/opt/xqa-shard/org/basex/examples/api/BaseXClient.py", line 116, in __init__
    self.__swrapper.connect((host, port))
  File "/opt/xqa-shard/org/basex/examples/api/BaseXClient.py", line 92, in <lambda>
    return lambda *arg, **kw: getattr(self.__s, name)(*arg, **kw)
ConnectionRefusedError: [Errno 111] Connection refused
[jsears@localhost xqa-perf]$

**Comment by jameshnsears** [comment]
shard's callapse in:
Debian 9 + Centos 7 guests + latest docker ce + latest virtualbox windows 10 host

**Comment by jameshnsears** [comment]
shards seem stable in **ubuntu 18.04** :-)
